name: Deploy to AKS

on: [push]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev  # Selects the dev environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Dev Environment Variable
        run: echo "Dev Environment Variable: $MY_ENV_VAR"
        env:
          MY_ENV_VAR: ${{ secrets.MY_ENV_VAR }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: deploy-dev  # Run this job only after dev deployment succeeds
    environment: test  # Selects the test environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Test Environment Variable
        run: echo "Test Environment Variable: $TEST_ENV_VAR"
        env:
          TEST_ENV_VAR: ${{ secrets.TEST_ENV_VAR }}
