name: Semantic Version Tagging

on:
  push:
    branches:
      - main  # Run only on pushes to the main branch

jobs:
  tag:
    runs-on: ubuntu-latest

    env:
      VERSION_PART: major  # Set to 'major', 'minor', or 'patch'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          # List all tags, sort by version, and get the latest one
          LATEST_TAG=$(git tag | sort -V | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="v0.0.0"
          fi
          echo "Latest tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Determine next version
        id: increment_version
        run: |
          # Remove 'v' prefix if it exists and parse major, minor, patch
          TAG=${LATEST_TAG#v}
          MAJOR=$(echo $TAG | cut -d. -f1)
          MINOR=$(echo $TAG | cut -d. -f2)
          PATCH=$(echo $TAG | cut -d. -f3)

          # Decide which part to increment based on VERSION_PART
          if [ "$VERSION_PART" = "major" ]; then
            MAJOR=$((MAJOR + 1))
            MINOR=0
            PATCH=0
          elif [ "$VERSION_PART" = "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          else
            PATCH=$((PATCH + 1))
          fi

          # Generate the next tag
          NEXT_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          echo "Next tag: $NEXT_TAG"
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV

      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Tag the commit with the next version tag
          git tag $NEXT_TAG
          # Push the new tag to the repository
          git push origin $NEXT_TAG

      - name: Print the new tag
        run: echo "Tagged with ${{ env.NEXT_TAG }}"
