name: Semantic Version Tagging

on:
  push:
    branches:
      - main
      - 'hotfix/*'  # Match any branch that starts with 'hotfix/'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine version increment based on branch
        id: determine_version_part
        run: |
          # Default to patch increment
          VERSION_PART="patch"

          # Check if the branch is 'main' or starts with 'hotfix/'
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            VERSION_PART="minor"
          elif [[ "${GITHUB_REF##*/}" =~ ^hotfix/ ]]; then
            VERSION_PART="patch"
          fi

          echo "VERSION_PART=$VERSION_PART" >> $GITHUB_ENV
          echo "Version increment type: $VERSION_PART"

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          # List all tags, sort by version, and get the latest one
          LATEST_TAG=$(git tag | sort -V | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="v0.0.0"
          fi
          echo "Latest tag: $LATEST_TAG"
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Determine next version
        id: increment_version
        run: |
          # Remove 'v' prefix if it exists and parse major, minor, patch
          TAG=${LATEST_TAG#v}
          MAJOR=$(echo $TAG | cut -d. -f1)
          MINOR=$(echo $TAG | cut -d. -f2)
          PATCH=$(echo $TAG | cut -d. -f3)

          # Increment version based on VERSION_PART
          if [ "$VERSION_PART" = "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [ "$VERSION_PART" = "patch" ]; then
            PATCH=$((PATCH + 1))
          fi

          # Generate the next tag
          NEXT_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          echo "Next tag: $NEXT_TAG"
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV

      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Tag the commit with the next version tag
          git tag $NEXT_TAG
          # Push the new tag to the repository
          git push origin $NEXT_TAG

      - name: Print the new tag
        run: echo "Tagged with ${{ env.NEXT_TAG }}"
