name: Semantic Version Tagging
on:
  push:
    branches:
      - main
      - 'hotfix/*'

jobs:
  tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch all tags
        run: git fetch --tags

      - name: Determine version increment based on branch
        id: determine_version_part
        run: |
          VERSION_PART="patch"
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            VERSION_PART="minor"
          elif [[ "${GITHUB_REF##*/}" =~ ^hotfix/ ]]; then
            VERSION_PART="patch"
          fi
          echo "VERSION_PART=$VERSION_PART" >> $GITHUB_ENV

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          LATEST_TAG=$(git tag | sort -V | tail -n 1)
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="v0.0.0"
          fi
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "::set-output name=latest_tag::$LATEST_TAG"

      - name: Determine next version
        id: increment_version
        run: |
          TAG=${LATEST_TAG#v}
          MAJOR=$(echo $TAG | cut -d. -f1)
          MINOR=$(echo $TAG | cut -d. -f2)
          PATCH=$(echo $TAG | cut -d. -f3)
          if [ "$VERSION_PART" = "minor" ]; then
            MINOR=$((MINOR + 1))
            PATCH=0
          elif [ "$VERSION_PART" = "patch" ]; then
            PATCH=$((PATCH + 1))
          fi
          NEXT_TAG="v${MAJOR}.${MINOR}.${PATCH}"
          echo "NEXT_TAG=$NEXT_TAG" >> $GITHUB_ENV
          echo "::set-output name=next_tag::$NEXT_TAG"

      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag $NEXT_TAG
          git push origin $NEXT_TAG

  build:
    runs-on: ubuntu-latest
    needs: tag  # This ensures the 'build' job runs only after the 'tag' job
    name: Build for branch ${{ github.ref_name }} by @${{ github.actor }} for commit message ${{ github.event.head_commit.message }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # - name: Login to Azure Container Registry (ACR)
      #   uses: azure/docker-login@v1
      #   with:
      #     login-server: <your-acr-name>.azurecr.io
      #     username: ${{ secrets.AZURE_USERNAME }}
      #     password: ${{ secrets.AZURE_PASSWORD }}

      # - name: Build Docker image with version tag
      #   run: |
      #     docker build . --file Dockerfile --tag <your-acr-name>.azurecr.io/my-image-name:${{ needs.tag.outputs.next_tag }}

      # - name: Push Docker image to ACR
      #   run: |
      #     docker push <your-acr-name>.azurecr.io/my-image-name:${{ needs.tag.outputs.next_tag }}
