name: List ENV Variables

on:
  push:
    branches: [ main ]

jobs:
  list-variables:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: List Windows ENV Variables
        shell: bash
        if : ${{ matrix.os == 'windows-latest' }}
        run: set

      - name: List Linux/MacOS ENV Variables
        shell: bash
        if : ${{ matrix.os != 'windows-latest' }}
        run: env
