name: Display URL in Deployment UI

on:
  push:
    branches:
      - main

jobs:
  display-url:
    runs-on: ubuntu-latest

    steps:
      - name: Display Preview URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/deployments \
            -f ref="${{ github.sha }}" \
            -f environment="preview" \
            -f description="Previewing URL" \
            -f environment_url="https://example.com/preview" \
            -f required_contexts=@- <<EOF
